<script lang="ts">
	import {
		IconArrowRight,
		IconBell,
		IconBold,
		IconBookmark,
		IconCheck,
		IconChevronRight,
		IconCircle,
		IconCompass,
		IconEdit,
		IconEye,
		IconEyeOff,
		IconHeart,
		IconItalic,
		IconLink,
		IconList,
		IconLogout,
		IconMenu2,
		IconMessageCircle,
		IconQuote,
		IconSearch,
		IconSend2,
		IconSettings,
		IconStar,
		IconTrash,
		IconThumbDown,
		IconThumbUp,
		IconWorld,
		IconUserCircle,
		IconX,
	} from "@tabler/icons-svelte"

	let { name, size = 20 }: { name: string; size?: number } = $props()
	const icons = {
		arrow: IconArrowRight,
		bell: IconBell,
		bold: IconBold,
		bookmark: IconBookmark,
		check: IconCheck,
		chevron: IconChevronRight,
		close: IconX,
		compass: IconCompass,
		edit: IconEdit,
		eye: IconEye,
		eyeOff: IconEyeOff,
		heart: IconHeart,
		italic: IconItalic,
		link: IconLink,
		list: IconList,
		logout: IconLogout,
		menu: IconMenu2,
		message: IconMessageCircle,
		quote: IconQuote,
		search: IconSearch,
		send: IconSend2,
		settings: IconSettings,
		star: IconStar,
		trash: IconTrash,
		thumbDown: IconThumbDown,
		thumbUp: IconThumbUp,
		world: IconWorld,
		user: IconUserCircle,
	}
	let SelectedIcon = $derived(icons[name as keyof typeof icons] ?? IconCircle)
</script>

<SelectedIcon {size} stroke={1.8} />
